# Generated by Django 5.2.4 on 2025-07-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20250726_0648'),
    ]

    operations = [
    ]
